# Generated by Django 3.1.2 on 2020-10-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('thumbnail', models.ImageField(max_length=500, null=True, upload_to='')),
                ('heart_count', models.IntegerField(default=0, null=True)),
                ('like', models.IntegerField(default=0, null=True)),
                ('retail_price', models.FloatField(default=0, null=True)),
                ('discount_percent', models.FloatField(default=0, null=True)),
                ('monthly_pay', models.FloatField(default=0, null=True)),
                ('monthly_payment', models.IntegerField(default=0, null=True)),
                ('detail_category', models.CharField(max_length=50, null=True)),
                ('cover_image', models.ImageField(max_length=500, null=True, upload_to='')),
                ('end_datetime', models.DateTimeField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.level')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Product_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.status')),
            ],
            options={
                'db_table': 'product_status',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ManyToManyField(null=True, through='product.Product_Status', to='product.Status'),
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_image', models.ImageField(max_length=500, null=True, upload_to='')),
                ('introduction_text', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'introduction',
            },
        ),
        migrations.CreateModel(
            name='DetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_image', models.URLField(max_length=300, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'detail_image',
            },
        ),
    ]
