# Generated by Django 3.1.2 on 2020-10-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(max_length=500, null=True, upload_to='usr'),
        ),
    ]
