# Generated by Django 3.1.1 on 2020-10-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201010_0743'),
        ('product', '0002_auto_20201008_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.creator'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='introduction_image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ManyToManyField(through='product.Product_Status', to='product.Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(max_length=500, null=True, upload_to=''),
        ),
    ]
