# Generated by Django 3.1.1 on 2020-10-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201010_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='hashtag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
